services:
    postgres:
        image: postgres:latest
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: ecommerce
        ports:
            - "5432:5432"
        volumes:
            - pgdata:/var/lib/postgresql/data

    rabbitmq:
        image: rabbitmq:4.2.0-management
        ports:
            - "5672:5672"
            - "15672:15672"
        environment:
            RABBITMQ_DEFAULT_USER: guest
            RABBITMQ_DEFAULT_PASSWORD: guest
volumes:
    pgdata:
